### ISSUE TITLE
Suggestion: Main GUI - Status Bar, Total from ALL Pools and Total BTC/DAY from All Workers

### ISSUE THREAD

**Issue by JimKnightster** [grantemsley/MultiPoolMiner#13]
Add up all Total BTC and Currency and total it in the status bar.  

Also if possible like on MPM.IO site, Total Worker BTC/DAY for all Workers

Maybe even Green/Red Status from workers as well.  

I know the 2nd 2 are available on the IO site, but would be convenient to have them on the GUI as well.

**Comment by grantemsley** [comment]
Already in the works my friend :)

**Comment by grantemsley** [comment]
Might wanna update to what I just committed :)

**Comment by JimKnightster** [comment]
Awesome, looking good.  Just a couple of things.  Worker Profit in status bar is using scientific notation on the number.  
![image](https://user-images.githubusercontent.com/13444381/38226824-750df7e6-36c9-11e8-9f63-d9d70bf99221.png) Right now its benchmarking the added algos so maybe it will correct itself when the number gets larger.  

Also I still dont see any miner stats on my main mining rig. Not sure if you worked on that or not, I know you were redoing that.  Im not sure why it doesnt show anything, my gaming rig works fine.

Both rigs are benchmarking so I will wait until they are done.  

All in all looks really good.  

I'm on the fence about the tabs, in some cases I like them, in others I don't but I will leave any comments alone for now until I have had more time.

**Comment by JimKnightster** [comment]
New GUI starts to benchmark some strange Dual mining algos but they are not listed in config.
![image](https://user-images.githubusercontent.com/13444381/38227432-2cfd50fc-36cc-11e8-99c7-2499c6cffbfa.png)

**Comment by grantemsley** [comment]
Will look into the status bar thing.

What do you mean you don't see miner stats?  Not sure what you're referring to there.  If you mean on the main tab, it takes a minute or so after starting for it to show, and may act weird during benchmarking.

I kind of like the tabs because I plan to add a few more of them, and once I do it will be too much to fit on one screen. If you've got better ideas I'm all ears though - I'm a much better programmer than designer.

I still have to rearrange a few things, and fix some of the buttons that don't work yet.  Then get log files showing.  But it's coming along nicely.

**Comment by grantemsley** [comment]
I just reverted the change with those algos.  Hadn't meant to push that just yet. Update again.

**Comment by JimKnightster** [comment]
yes the Main page still doesnt show active miners or anything on my main 6gpu system. I was thinking its might be because of benchmarking so I will wait, I thought it might be the same with the older program, but they never showed even after hours.  

I was thinking on the tabs, maybe an overview page, with Balances and Worker status (with colors) on one page, will give a nice overview of the entire operation.  Keep in mind I am a small time miner, maybe with several rigs that might be too crowded, but for me it would be nice to see all pertinent info at a glance.

**Comment by grantemsley** [comment]
What do you see if you open a browser on that machine and go to  http://localhost:3999/activeminers ?

It should show up even during benchmarking, just with speeds listed as 0.

**Comment by JimKnightster** [comment]
A json? file with a whole lot of API data listed for a bunch (all?) miners.  want a copy?

**Comment by grantemsley** [comment]
Hmm...if it's showing the JSON there it should be showing it in the launcher.  That's odd.

What currencies do you have in your config.txt file?  An error there might do it.

**Comment by JimKnightster** [comment]
"Currency":  [
                     "BTC",
                     "USD"
                 ],

**Comment by grantemsley** [comment]
Well that looks fine...hmm.  

Oh...I have you the wrong url to test.  Replace /activeminers with /runningminers and what do you see?

**Comment by JimKnightster** [comment]
Just a couple of miners, but I see your address and workernames.

**Comment by JimKnightster** [comment]
I think that is the high DCRI valued Algo you pulled out, I havent updated my main rig yet

**Comment by grantemsley** [comment]
Hmm.  Can you post the output from that url, your config.txt file and a zip file of the logs directory?

I want to see if I can replicate the problem on my system.

**Comment by JimKnightster** [comment]
Let me update it it, and try again without the new algo's in there then I will.  30 minutes or so

**Comment by grantemsley** [comment]
Alright.  I'm off to bed anyways, I'll take a look at what you post in the morning.

**Comment by JimKnightster** [comment]
[config.txt](https://github.com/grantemsley/MultiPoolMiner/files/1870177/config.txt)
[runningminers.txt](https://github.com/grantemsley/MultiPoolMiner/files/1870179/runningminers.txt)
[Logs.zip](https://github.com/grantemsley/MultiPoolMiner/files/1870180/Logs.zip)

FYI, after resetting everything but stats, neither Rigs GUI is showing Active Miners

**Comment by JimKnightster** [comment]
A couple of things I noticed today Worker Profit in status bar displays a 0 now.

As I was looking around I decided to load launcher.ps1 into the ISE and run it from there, as I was looking at my other PC the Active Miners all of a sudden started to display.  I was thinking maybe it was because I ran from the ISE and switched back to that computer, then they disappeared again... :(  Haven't been able to get them back.

**Comment by grantemsley** [comment]
Running the launcher from the ISE can cause problems because the ISE doesn't handle runspaces properly.  So I wouldn't recommend testing anything that way (usually the ISE will just crash after a bit)

I looked over the logs you posted and nothing really stands out as being wrong there.  Except that the multipoolminer logs are pretty short - how long was it running?  Were you stopping and starting it again?

**Comment by JimKnightster** [comment]
I normally dont run it from the ISE was just playing around with some of the variables trying to find out where the Active Miner info was.

Yeah that was right after a clean install, I can send you MPM logs from this machine if you want, its been running all day

**Comment by JimKnightster** [comment]
I also see a lot of 0 byte log files that have the name of the miner and the date transposed, I think there is a typo or something in the logging functions.  

I.e. I see this for every miner in the logs folder:
![image](https://user-images.githubusercontent.com/13444381/38285514-888bd4ee-378e-11e8-8893-5a8e51ebb5b3.png)
![image](https://user-images.githubusercontent.com/13444381/38285588-deb14afc-378e-11e8-99b6-f6d00fb8e3a0.png)

Notice the files that start with a date/time are 0 bytes, but the ones that start with the miner name have content in them.  I don't think this is the issue you thought it was where the files were getting called before they were created, this seems to be a bug in one of the logging routines where the filename is getting created incorrectly then getting corrected somewhere else.  

Q: would you rather keep this in one thread for now, or would it be easier to track if each had their own issue?

**Comment by JimKnightster** [comment]
More logs 
[Logs.zip](https://github.com/grantemsley/MultiPoolMiner/files/1874257/Logs.zip)
